"use client";

import { useMemo, useRef, useState } from "react";
import { Check, ChevronDown, Volume2 } from "lucide-react";

const words = [["зид","стена"],["тајна","секрет"],["дирати","трогать"],["још увек","всё ещё"],["увек","всегда"],["стигла","приехала"],["него","но"],["улаз","вход"],["углавном","в основном"],["понашати се","вести себя"],["озбиљно","серьёзно"],["док","пока"],["потрчати","побежать"],["баш","именно"],["пронаћи","найти"]] as const;
const verbs = [["сести","сео / села"],["ићи","ишао / ишла"],["волети","волео / волела"],["сањати","сањао / сањала"],["знати","знао / знала"],["ручати","ручао / ручала"],["носити","носио / носила"]];
const quiz = [["Јуче сам ___ код куће.","седео",["седео","седим","сешћу"]],["Маша је ___ машну.","носила",["носи","носила","носиће"]],["Ми смо ___ историју.","волеле",["волимо","волеле","волећемо"]],["Он није ___ одговор.","знао",["зна","знао","знаће"]]] as const;
const extraWords = [["одморити се","отдохнуть"],["сигуран/на","уверен/а"],["споменик","памятник"],["рођак","родственник"],["дугме","пуговица"],["молба","просьба"]] as const;
let activeLessonAudio: HTMLAudioElement | null = null;

function LessonAudioPlayer({ src, label, transcript }: { src: string; label: string; transcript: string }) {
  const audioRef = useRef<HTMLAudioElement>(null);
  const [speed, setSpeed] = useState<1 | 1.5>(1);
  const [showTranscript, setShowTranscript] = useState(false);
  const toggleSpeed = () => { const next = speed === 1 ? 1.5 : 1; setSpeed(next); if (audioRef.current) audioRef.current.playbackRate = next; };
  return <div className="mt-5 rounded-xl border-2 border-ink bg-blue-50 p-4 shadow-[3px_3px_0_#202124]"><p className="mb-3 flex items-center gap-2 font-black"><Volume2 size={20} aria-hidden /> Послушај · {label}</p><audio ref={audioRef} controls preload="none" onPlay={()=>{const audio=audioRef.current;if(!audio)return;if(activeLessonAudio&&activeLessonAudio!==audio)activeLessonAudio.pause();activeLessonAudio=audio;}} className="w-full" aria-label={label}><source src={src} type="audio/mp4" />Ваш браузер не поддерживает аудио.</audio><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={toggleSpeed} className="min-h-11 rounded-full border-2 border-ink bg-white px-4 font-black">{speed}× / {speed === 1 ? "1,5×" : "1×"}</button><button type="button" onClick={()=>setShowTranscript(v=>!v)} className="min-h-11 rounded-full border-2 border-ink bg-white px-4 font-black">{showTranscript ? "Скрыть текст" : "Показать текст"}</button></div>{showTranscript?<div className="mt-3 rounded-lg border-2 border-ink/20 bg-white p-4 whitespace-pre-line"><p className="text-sm font-black uppercase tracking-[.12em] text-ink/60">Текст аудио</p><p className="mt-2">{transcript}</p></div>:null}<p className="mt-3 text-xs font-bold text-ink/55">Аудио добавим позже — интерфейс уже готов.</p></div>;
}

const dušan = [["око 1308.","Рођен је Стефан Душан, син краља Стефана Дечанског."],["1331.","Постао је краљ Србије."],["1346.","У Скопљу је крунисан за цара Срба и Грка."],["1349. и 1354.","Донео је Душанов законик."],["1355.","Умро је, а после његове смрти царство је почело да се распада."]];

export default function LessonSeventeenExperience() {
  const [open,setOpen]=useState<number|null>(null); const [comicTranslation,setComicTranslation]=useState(false); const [answers,setAnswers]=useState<Record<string,string>>({}); const [checked,setChecked]=useState(false); const [done,setDone]=useState(false); const [selectedWord,setSelectedWord]=useState<string|null>(null); const [matched,setMatched]=useState<string[]>([]);
  const score=useMemo(()=>quiz.filter(([,correct],i)=>answers[String(i)]===correct).length,[answers]);
  return <main id="lesson-17-start" className="bg-[#f8f1e7] px-4 py-10 sm:px-6 sm:py-16"><div className="mx-auto max-w-4xl">
    <div className="border-2 border-ink bg-serbian-blue p-6 text-white shadow-[7px_7px_0_#e83d34] sm:p-10"><p className="font-black uppercase tracking-[.18em] text-[#ffd55c]">lekcija 17 · prošlo vreme</p><h2 className="mt-3 text-4xl font-black leading-tight sm:text-6xl">Učimo srpski: prošlo vreme</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/85">Путешествуем с Машей во времени, учимся рассказывать, что произошло вчера, и в конце читаем о Душановом царстве.</p><a href="#strip" className="mt-7 inline-flex rounded-full bg-serbian-red px-6 py-3 font-black shadow-[3px_3px_0_#202124]">Počinjemo ↓</a></div>

    <section id="strip" className="scroll-mt-20 pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">1. nove reči</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Речи пре читања</h2><p className="mt-2 text-ink/70">Прво погледај речи, па слушај и читај стрип.</p><div className="mt-5 grid grid-cols-2 gap-x-5 gap-y-3 border-2 border-ink bg-white p-5 shadow-comic sm:grid-cols-3">{words.map(([sr,ru])=><div key={sr} className="border-b border-ink/20 pb-2"><p className="font-black">{sr}</p><p className="text-sm text-ink/65">{ru}</p></div>)}</div><LessonAudioPlayer src="/audio/lesson-17/01-reci-pre-citanja.m4a" label="Речи пре читања" transcript="Зид — стена. Тајна — секрет. Дирати — трогать. Још увек — всё ещё. Увек — всегда. Стићи — прибыть. Него — но. Улаз — вход. Углавном — в основном. Понашати се — вести себя. Озбиљно — серьёзно. Док — пока. Потрчати — побежать. Баш — именно. Пронаћи — найти."/><details className="mt-4 border-2 border-ink bg-white p-4"><summary className="cursor-pointer font-black">Још речи из лекције</summary><div className="mt-3 grid gap-x-5 gap-y-2 sm:grid-cols-2">{extraWords.map(([sr,ru])=><p key={sr}><strong>{sr}</strong><span className="text-ink/65"> — {ru}</span></p>)}</div></details><p className="mt-10 font-black uppercase tracking-[.16em] text-serbian-red">2. strip</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Маша и времеплов</h2><button type="button" onClick={()=>window.speechSynthesis?.speak(new SpeechSynthesisUtterance("Pismo nas je dovelo baš ovde. Ovo je vremenska mašina. Maša je prvo upala na dvor cara Dušana. Tamo je upoznala viteza Živka Guščića. Zajedno su pronašli zupčanik i vratili se kući."))} className="mt-5 inline-flex items-center gap-2 rounded-lg border-2 border-ink bg-serbian-blue px-5 py-3 font-black text-white shadow-[3px_3px_0_#202124]"><Volume2 size={18}/> Читање стрипа</button><figure className="mt-5 overflow-hidden border-2 border-ink bg-white shadow-comic"><a href="/images/lesson-17-dušan-comic.webp" target="_blank" rel="noreferrer" className="block" aria-label="Отвори стрип крупно"><img src="/images/lesson-17-dušan-comic.webp" alt="Оригинални стрип: Маша, коњ и гуска путују кроз време до двора цара Душана" className="h-auto w-full" /></a><figcaption className="border-t-2 border-ink bg-[#fff4d6] px-4 py-3 text-sm font-bold">Кликни на слику да отвориш стрип крупно.</figcaption></figure><button type="button" onClick={()=>setComicTranslation(v=>!v)} className="mt-5 rounded-lg border-2 border-ink bg-white px-5 py-3 font-black shadow-[3px_3px_0_#202124]">Превод стрипа</button>{comicTranslation?<div className="mt-4 border-2 border-ink bg-[#eff8fe] p-5 leading-7 shadow-comic"><p><strong>Маша, лошадь и гусь</strong> находят машину времени. Маша падает во двор царя Душана, знакомится с рыцарем Живко Гушчичем, а затем помогает найти шестерёнку. Благодаря ей путешественники могут вернуться домой.</p></div>:null}</section>

    <section className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">3. prošlo vreme</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Перфекат</h2><button type="button" className="mt-5 inline-flex items-center gap-2 rounded-lg border-2 border-ink bg-serbian-blue px-5 py-3 font-black text-white shadow-[3px_3px_0_#202124]"><Volume2 size={18}/> Објашњење: како се гради перфекат</button><p className="mt-3 text-sm text-ink/65">Овде ћемо додати твоје аудио-објашњење и нову табелу.</p><div className="mt-5 border-2 border-ink bg-[#fff7d6] p-5 leading-7 shadow-comic"><p>Когда действие уже закончилось, используем <strong>перфекат</strong>.</p><p className="mt-3 font-black">сам / си / је / смо / сте / су + радни глаголски придев</p><p>Јуче сам <strong>седео</strong> код куће. Јелена је <strong>сањала</strong> море. Ми смо <strong>волеле</strong> историју.</p><p className="mt-3">Местоимение часто опускаем: <strong>Волела сам историју.</strong> В отрицании: <strong>Нисам волела историју.</strong></p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{verbs.map(([inf,form])=><div key={inf} className="border-2 border-ink bg-white p-4"><p className="font-black">{inf}</p><p className="mt-2 text-xl font-black text-serbian-red">он је {form}</p></div>)}</div><div className="mt-5 border-2 border-ink bg-white p-5 shadow-comic"><p className="font-black">Прочитай и сравни</p><p className="mt-2">Маша носи машну. <strong>Маша је носила машну.</strong></p><p>Волим да спавам недељом. <strong>Волела сам да спавам недељом.</strong></p><button type="button" onClick={()=>window.speechSynthesis?.speak(new SpeechSynthesisUtterance("Juče sam sedeo kod kuće, i uveče sam išao da šetam."))} className="mt-4 inline-flex items-center gap-2 rounded-lg border-2 border-ink bg-white px-4 py-3 font-black shadow-[3px_3px_0_#202124]"><Volume2 size={18}/> Слушать пример</button></div></section>

    <section className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">4. vežba</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Выбери форму в прошедшем времени</h2><div className="mt-5 space-y-4">{quiz.map(([text,correct,options],i)=><div key={text} className="border-2 border-ink bg-white p-5 shadow-comic"><p className="font-black">{i+1}. {text}</p><div className="mt-3 flex flex-wrap gap-2">{options.map(o=><button type="button" key={o} onClick={()=>{setAnswers(a=>({...a,[i]:o}));setChecked(false)}} className={"rounded-lg border-2 border-ink px-4 py-2 font-bold "+(answers[String(i)]===o?"bg-serbian-blue text-white":"bg-white")}>{o}</button>)}</div>{checked&&answers[String(i)]?<p className={"mt-3 font-black "+(answers[String(i)]===correct?"text-green-700":"text-serbian-red")}>{answers[String(i)]===correct?"Тачно!":"Тачан одговор: "+correct}</p>:null}</div>)}</div><button type="button" onClick={()=>setChecked(true)} className="mt-5 rounded-lg border-2 border-ink bg-serbian-red px-5 py-3 font-black text-white shadow-[3px_3px_0_#202124]">Проверить</button>{checked?<p className="mt-4 border-2 border-ink bg-white p-4 font-black">Результат: {score} / {quiz.length}</p>:null}</section>

    <section className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">5. čitamo</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Бруно и историја Србије</h2><div className="mt-5 border-2 border-ink bg-white p-5 leading-8 shadow-comic"><p>Јуче је Бруно био на <strong className="text-serbian-red">ручку</strong> код својих српских пријатеља Душана и Јелене. Разговарали су о историји Србије и о политичкој ситуацији на Балкану.</p><p className="mt-3">Бруно је одувек волео историју и много је <strong className="text-serbian-red">читао</strong> о историји Француске. Али није много знао о историји Србије. Није знао колико је српска држава била јака почетком четрнаестог века када је владао цар Душан Силни.</p><p className="mt-3">После <strong className="text-serbian-red">посете</strong> пријатељима Бруно је дуго шетао градом и размишљао о Србији. На крају је решио да пише блог под називом „Моја Србија“. Увече је дуго седео за рачунаром и правио план.</p></div><div className="mt-4 grid gap-2 border-2 border-ink bg-[#eff8fe] p-4 sm:grid-cols-3"><p><strong>ручак</strong> — обед</p><p><strong>одувек</strong> — всегда</p><p><strong>посета</strong> — визит</p><p><strong>владао</strong> — правил</p><p><strong>решио</strong> — решил</p><p><strong>план</strong> — план</p></div></section>
<section className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">6. se</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Običaji su se promenili</h2><div className="mt-5 border-2 border-ink bg-white p-5 leading-8 shadow-comic"><p><strong>Дружио сам се.</strong> <strong>Нисам се дружио.</strong> <strong>Да ли си се дружио?</strong></p><p className="mt-3">Учитељи су се сећали имена својих ученика. Смејали смо се на часовима. Туристи су се шетали улицама. Зашто се ниси јавио на телефон? Да ли сте се спремали за испит? Бринула сам се за вас. Душан и Јелена су се волели.</p></div></section>
<section className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">7. razgovaramo</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Причамо о јуче</h2><div className="mt-5 space-y-3 border-2 border-ink bg-white p-5 leading-7 shadow-comic"><p>Који дан је био јуче? Испричај свој јучерашњи дан.</p><p>О чему су разговарали Бруно, Душан и Јелена?</p><p>Шта је Бруно сазнао о цару Душану?</p><p>Шта је радио Бруно после ручка?</p></div></section>
<section className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">8. kultura</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Kum nije dugme</h2><div className="mt-5 border-2 border-ink bg-[#fff7d6] p-5 leading-8 shadow-comic"><p>У српској култури кумство је веома важно. Кум није само гост на венчању или крштењу, већ блиска особа и члан породице. Израз <strong>„Кум није дугме“</strong> значи да се кум бира пажљиво и да његово место има посебну вредност.</p></div></section>

    <section id="dusan" className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">5. na kraju puta</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Dušanovo carstvo</h2><div className="mt-5 border-2 border-ink bg-white p-5 leading-8 shadow-comic"><p><strong>Стефан Урош IV Душан</strong>, познат као цар Душан, био је српски средњовековни владар. За време његове владавине Србија је постала највећа и најмоћнија држава на Балкану.</p><p className="mt-4">Душан је освојио велике територије. У Скопљу је крунисан за цара Срба и Грка. Желео је снажну државу са јасним законима.</p><p className="mt-4">Донео је Душанов законик, који је уређивао судове, градове, села, цркву и обавезе властеле. После његове смрти царство је почело да се распада.</p></div><div className="mt-5 space-y-3">{dušan.map(([date,text],i)=><button type="button" key={date} onClick={()=>setOpen(open===i?null:i)} className="w-full border-2 border-ink bg-white p-4 text-left shadow-[3px_3px_0_#202124]"><div className="flex items-center justify-between gap-4"><span className="font-black text-serbian-red">{date}</span><ChevronDown className={open===i?"rotate-180 transition":"transition"}/></div>{open===i?<p className="mt-3 leading-7">{text}</p>:<p className="mt-1 text-sm text-ink/65">Нажми, чтобы открыть</p>}</button>)}</div></section>

    <section className="mt-14 border-2 border-ink bg-serbian-blue p-6 text-white shadow-[7px_7px_0_#e83d34] sm:p-8"><p className="font-black uppercase tracking-[.16em] text-[#ffd55c]">domaći zadatak</p><h2 className="mt-2 text-3xl font-black">Маша после путешествия</h2><ol className="mt-4 list-decimal space-y-2 pl-6 leading-7"><li>Напиши 5 предложений: где Маша была, что она видела и что она делала.</li><li>Используй минимум 3 формы перфекта.</li><li>Добавь одно предложение о царе Душане.</li></ol><button type="button" onClick={()=>setDone(true)} className="mt-6 inline-flex items-center gap-2 rounded-lg border-2 border-ink bg-white px-5 py-3 font-black text-serbian-blue shadow-[3px_3px_0_#202124]"><Check size={18}/> Завершить урок</button>{done?<p className="mt-5 rounded-lg bg-white/15 p-4 text-xl font-black">Браво! Сада можеш да причаш у прошлом времену. 🎉</p>:null}</section>
  </div></main>;
}