"use client";

import { useEffect, useMemo, useState } from "react";

const STEP_NAMES = ["Диалоги", "Профессии", "Стрип", "Новые слова", "Местоимения", "Глагол biti", "Вежба", "Поређење", "Фразы", "Домаћи"];
const PAIRS = [["veliki grad", "большой город"], ["samo", "всего лишь"], ["konobarica", "официантка"], ["kuvarica", "повариха"], ["želeti, želim", "хотеть"], ["treba", "надо"], ["baš", "очень"], ["morati, moram", "должен / должна"], ["pametna", "умная"]];
const FORMS = ["сам", "си", "је", "смо", "сте", "су"];
const QUESTIONS = [["Ја ___ лекарка.", "сам"], ["Ти ___ учитељица.", "си"], ["Он ___ бизнисмен.", "је"], ["Она ___ програмерка.", "је"], ["Ми ___ менаџери.", "смо"], ["Ви ___ политичари.", "сте"], ["Оне ___ фризерке.", "су"]];
const PROFESSIONS = ["учитељ / учитељица", "васпитач / васпитачица", "певач / певачица", "конобар / конобарица", "кувар / куварица", "ученик / ученица", "службеник / службеница", "научник / научница", "комшија / комшиница", "колега / колегиница", "професор / професорка", "новинар / новинарка", "лекар / лекарка", "министар / министарка", "политичар / политичарка", "полицајац / полицајка", "менаџер / менаџерка", "инжењер / инжењерка", "фризер / фризерка", "пензионер / пензионерка", "програмер / програмерка", "фудбалер / фудбалерка", "апотекар / апотекарка", "ветеринар / ветеринарка", "сликар / сликарка", "уметник / уметница", "економиста / економисткиња", "студент / студенткиња"];
const IMAGE = (file: string) => `https://ty-serb-lesson-two.lixi141210.chatgpt.site/lesson-02/images/${file}`;

function AudioSlot({ title, transcript }: { title: string; transcript: string }) { const [open, setOpen] = useState(false); return <div className="mt-6 border-2 border-ink bg-blue-50 p-4 shadow-comic"><p className="font-black">🔊 Лидијино аудио: {title}</p><p className="mt-1 text-sm text-ink/65">Место для записи готово — аудио добавится сюда без изменения структуры урока.</p><button type="button" onClick={() => setOpen(!open)} className="mt-3 border-2 border-ink bg-white px-4 py-2 font-black">{open ? "Скрыть текст" : "Показать текст аудио"}</button>{open ? <p className="mt-3 border-t-2 border-ink pt-3 leading-7">{transcript}</p> : null}</div>; }
function Shell({ title, children }: { title: string; children: React.ReactNode }) { return <div className="border-2 border-ink bg-white p-5 shadow-comic sm:p-8"><p className="font-black uppercase tracking-[.16em] text-serbian-red">Лекција 02</p><h2 className="mt-2 text-3xl font-black sm:text-5xl">{title}</h2>{children}</div>; }

export default function LessonTwoExperience() {
  const [step, setStep] = useState(0); const [done, setDone] = useState<number[]>([]); const [word, setWord] = useState<number | null>(null); const [solved, setSolved] = useState<number[]>([]); const [answers, setAnswers] = useState<Record<number,string>>({}); const [checked, setChecked] = useState(false);
  const translations = useMemo(() => PAIRS.map(([, text], index) => ({ text, index })).reverse(), []);
  useEffect(() => { const saved = JSON.parse(localStorage.getItem("ty-serb:lesson-2") || "{}"); setDone(saved.done || []); }, []);
  function next(){ const result = [...new Set([...done, step])]; setDone(result); localStorage.setItem("ty-serb:lesson-2", JSON.stringify({ done: result })); setStep(Math.min(step + 1, STEP_NAMES.length - 1)); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function selectTranslation(index:number){ if(word === index) setSolved(s => s.includes(index) ? s : [...s,index]); setWord(null); }
  return <section className="bg-[#f8f1e7] px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><div className="sticky top-0 z-20 -mx-4 border-b-2 border-ink bg-white px-4 py-3 sm:mx-0 sm:px-0"><div className="flex gap-2 overflow-x-auto pb-1">{STEP_NAMES.map((name,index)=><button key={name} type="button" onClick={()=>setStep(index)} className={`min-h-11 shrink-0 border-2 px-3 text-sm font-black ${step===index?"border-serbian-red bg-serbian-red text-white":"border-ink bg-white"}`}>{index+1}. {done.includes(index)?"✓ ":""}{name}</button>)}</div></div><div className="pt-8">
  {step===0?<Shell title="На пасошкој контроли"><div className="mt-6 grid gap-4 md:grid-cols-2"><article className="border-2 border-ink p-5"><b>Пасошка контрола</b><p className="mt-3 leading-8">— Добро јутро!<br/>— Добро јутро! Ваш пасош, молим.<br/>— Изволите.<br/>— Ви сте господин Бонд?<br/>— Да, ја сам Стив Бонд.<br/>— Ви сте туриста?<br/>— Не, ја сам бизнисмен.<br/>— Ваша адреса у Београду?<br/>— Хотел „Метропол“.<br/>— Изволите пасош.<br/>— Хвала.</p></article><article className="border-2 border-ink p-5"><b>Сусрет <span className="text-serbian-red">— встреча</span></b><p className="mt-3 leading-8">— Извините, да ли сте ви господин Бонд?<br/>— Да, ја сам Стив Бонд.<br/>— Ја сам Љиљана Јовановић.<br/>— Драго ми је.<br/>— Ви сте Енглез?<br/>— Да, ја сам Енглез.<br/>— Добро говорите српски!<br/>— Хвала.</p></article></div><AudioSlot title="Диалоги: Стив Бонд" transcript="Прочитай оба диалога медленно, с короткой паузой после каждой реплики."/></Shell>:null}
  {step===1?<Shell title="Данас учимо о професијама!"><p className="mt-4 text-lg">Danas učimo o profesijama! Обрати пажњу како се граде називи у женском роду.</p><div className="mt-6 grid gap-2 sm:grid-cols-2 md:grid-cols-3">{PROFESSIONS.map((item,i)=><div key={item} className="border-2 border-ink p-3 font-bold"><span className="mr-2 text-xs text-serbian-red">{String(i+1).padStart(2,"0")}</span>{item}</div>)}</div><AudioSlot title="Изговор професија" transcript="Прочитай пары: учитељ — учитељица; васпитач — васпитачица; певач — певачица… с паузой после каждой пары."/></Shell>:null}
  {step===2?<Shell title="Ana, konj u velikom gradu!"><p className="mt-4 font-bold text-serbian-red">Пролистай все кадры стрипа по порядку.</p><div className="mt-6 flex snap-x gap-4 overflow-x-auto pb-4">{[1,2,3,4,5,6,7].map(n=><figure key={n} className="w-[88vw] shrink-0 snap-center sm:w-[720px]"><img src={IMAGE(`lesson-02-comic-0${n}.jpg`)} alt={`Стрип Ана, кадар ${n} из 7`} className="w-full border-2 border-ink"/><figcaption className="mt-2 text-right font-black text-ink/60">{n}/7</figcaption></figure>)}</div><AudioSlot title="Стрип" transcript="Прочитай реплики стрипа от начала до конца. Сохраняй интонацию диалога."/></Shell>:null}
  {step===3?<Shell title="Непознате речи"><p className="mt-4 text-ink/70">Нажми на сербское слово, затем на русский перевод.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="space-y-2">{PAIRS.map(([text],i)=><button key={text} disabled={solved.includes(i)} onClick={()=>setWord(i)} className={`w-full border-2 p-3 text-left font-black ${solved.includes(i)?"border-serbian-blue bg-serbian-blue text-white":word===i?"border-serbian-red bg-serbian-red text-white":"border-ink"}`}>{text}</button>)}</div><div className="space-y-2">{translations.map(({text,index})=><button key={text} disabled={solved.includes(index)} onClick={()=>selectTranslation(index)} className={`w-full border-2 p-3 text-left font-bold ${solved.includes(index)?"border-serbian-blue bg-serbian-blue text-white":"border-ink"}`}>{text}</button>)}</div></div><p className="mt-4 font-black text-serbian-blue">{solved.length===PAIRS.length?"Браво! Все слова соединены.":`Готово: ${solved.length}/${PAIRS.length}`}</p></Shell>:null}
  {step===4?<Shell title="Личные местоимения — nominativ"><p className="mt-3 text-lg font-bold text-serbian-blue">Кто? Что?</p><div className="mt-6 grid border-2 border-ink sm:grid-cols-2"><div className="border-b-2 border-ink p-5 sm:border-b-0 sm:border-r-2"><p className="font-black uppercase tracking-[.14em]">Singular / Jednina</p><div className="mt-5 space-y-4 text-4xl font-black">ја <span className="text-base font-normal text-ink/55">я</span><br/>ти <span className="text-base font-normal text-ink/55">ты</span><br/>он<br/>она<br/>оно</div></div><div className="p-5"><p className="font-black uppercase tracking-[.14em] text-serbian-blue">Plural / Množina</p><div className="mt-5 space-y-4 text-4xl font-black text-serbian-blue">ми <span className="text-base font-normal text-ink/55">мы</span><br/>ви / Ви<br/>они<br/>оне<br/>она</div><p className="mt-4 text-serbian-red">Ви — вежливая форма</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><p className="border-2 border-ink p-4 text-xl font-black"><span className="text-serbian-blue">Оне</span> <span className="text-serbian-red">су</span> ученице.<br/><span className="text-base font-normal text-ink/55">Они ученицы.</span></p><p className="border-2 border-ink p-4 text-xl font-black">Два места <span className="text-serbian-red">су</span> за <span className="text-serbian-blue">вас</span>.<br/><span className="text-base font-normal text-ink/55">Два места для вас.</span></p></div></Shell>:null}
  {step===5?<Shell title="Глагол ЈЕСАМ (бити)"><p className="mt-4 text-lg leading-8">В сербском глагол <b>бити</b> обязателен: он связывает <b>с существительным</b>, <b>прилагательным</b>, местом и состоянием.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><p className="border-2 border-ink p-4"><b>С существительным</b><br/>Ја сам студент. <span className="text-ink/55">— Я студент.</span></p><p className="border-2 border-ink p-4"><b>С прилагательным</b><br/>Она је лепа. <span className="text-ink/55">— Она красивая.</span></p><p className="border-2 border-ink p-4"><b>С местом</b><br/>Ми смо код куће. <span className="text-ink/55">— Мы дома.</span></p><p className="border-2 border-ink p-4"><b>С состоянием</b><br/>Ја сам гладна. <span className="text-ink/55">— Я голодна.</span></p></div><div className="mt-6 border-l-8 border-serbian-red bg-blue-50 p-5"><b>Прошло време</b><p className="mt-2 leading-7">В прошедшем времени форма меняется по роду и числу: <b>Радила сам цео дан.</b> — Я работала весь день. <b>Јуче сте били у позоришту.</b> — Вчера вы были в театре. В сербском вспомогательный глагол остаётся: <b>сам, си, је, смо, сте, су</b>.</p></div><AudioSlot title="Облици глагола бити" transcript="Ја сам. Ти си. Он, она, оно је. Ми смо. Ви сте. Они, оне, она су. Прочитай затем примеры с существительным, прилагательным, местом и состоянием."/></Shell>:null}
  {step===6?<Shell title="Провери глагол biti"><p className="mt-4 text-ink/70">Нажми на правильную форму — писать не нужно.</p><div className="mt-6 space-y-4">{QUESTIONS.map(([q,correct],i)=><div key={q} className="border-2 border-ink p-4"><p className="font-black">{i+1}. {q}</p><div className="mt-3 flex flex-wrap gap-2">{FORMS.map(form=><button key={form} onClick={()=>{setAnswers({...answers,[i]:form});setChecked(false)}} className={`border-2 px-4 py-2 font-black ${answers[i]===form?"border-serbian-red bg-serbian-red text-white":"border-ink bg-white"}`}>{form}</button>)}</div>{checked&&answers[i]!==correct?<p className="mt-2 font-bold text-serbian-red">Правильно: {correct}</p>:null}</div>)}</div><button onClick={()=>setChecked(true)} className="mt-6 border-2 border-ink bg-serbian-blue px-5 py-3 font-black text-white">Проверить</button>{checked?<p className="mt-4 font-black">Результат: {QUESTIONS.filter(([,correct],i)=>answers[i]===correct).length}/{QUESTIONS.length}</p>:null}</Shell>:null}
  {step===7?<Shell title="Упоредимо српски и руски"><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="border-2 border-ink p-5"><b>Руски</b><p className="mt-3 text-lg leading-8">Я студент.<br/>Она дома.<br/>Мы умнейшие.</p></div><div className="border-2 border-ink bg-serbian-blue p-5 text-white"><b>Српски</b><p className="mt-3 text-lg leading-8">Ја <span className="font-black text-[#ffb6b9]">САМ</span> студент.<br/>Она <span className="font-black text-[#ffb6b9]">ЈЕ</span> код куће.<br/>Ми <span className="font-black text-[#ffb6b9]">СМО</span> најпаметнији.</p></div></div><div className="mt-5 border-2 border-ink p-5"><b>Показна заменица + БИТИ + именица</b><p className="mt-3 leading-8">Ово <span className="font-black text-serbian-red">ЈЕ</span> кућа.<br/>То <span className="font-black text-serbian-red">ЈЕ</span> мој брат.<br/>Оно <span className="font-black text-serbian-red">СУ</span> деца.</p></div></Shell>:null}
  {step===8?<Shell title="Фразе за час"><div className="mt-6 grid gap-4 sm:grid-cols-2"><p className="border-2 border-ink p-4"><b>Извините…</b><br/>Извините, шта значи ова реч?<br/>Шта ово значи?<br/>Како се пише? Како се чита?</p><p className="border-2 border-ink p-4"><b>Објашњења</b><br/>Је л’ можете да поновите?<br/>Молим Вас, поновите, нисам разумео/разумела.<br/>Не разумем…</p><p className="border-2 border-ink p-4"><b>Како да кажем</b><br/>Нисам сигуран/сигурна.<br/>Професоре/Професорка…<br/>Могу ли да Вас нешто питам?</p><p className="border-2 border-ink p-4"><b>Је л’ говорите српски?</b><br/>Да, (по)мало. Говорим (по)мало.<br/>Разумем помало. Знам нешто.</p></div></Shell>:null}
  {step===9?<Shell title="Вежбе за код куће"><p className="mt-4">Открывай задания здесь, внутри урока. Они не уводят тебя на другой сайт.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><iframe title="Новые слова" src="https://learningapps.org/watch?v=pvoby9i1k26" className="h-[560px] w-full border-2 border-ink"/><iframe title="Упиши глагол бити" src="https://learningapps.org/watch?v=p6pbz143t26" className="h-[560px] w-full border-2 border-ink"/></div></Shell>:null}
  <div className="mt-6 flex items-center justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>{setStep(step-1);window.scrollTo({top:0,behavior:"smooth"})}} className="border-2 border-ink bg-white px-5 py-3 font-black disabled:opacity-40">← Назад</button><button type="button" onClick={next} className="border-2 border-ink bg-serbian-red px-5 py-3 font-black text-white">{step===STEP_NAMES.length-1?"Завершить урок ✓":"Сделано, дальше →"}</button></div>
 </div></div></section>;
}
