const professions = ["учитељ / учитељица", "васпитач / васпитачица", "певач / певачица", "конобар / конобарица", "кувар / куварица", "ученик / ученица", "службеник / службеница", "научник / научница", "комшија / комшиница", "колега / колегиница", "професор / професорка", "новинар / новинарка", "лекар / лекарка", "министар / министарка", "политичар / политичарка", "полицајац / полицајка", "менаџер / менаџерка", "инжењер / инжењерка", "фризер / фризерка", "пензионер / пензионерка", "програмер / програмерка", "фудбалер / фудбалерка", "апотекар / апотекарка", "ветеринар / ветеринарка", "сликар / сликарка", "уметник / уметница", "економиста / економисткиња", "студент / студенткиња"];

function Block({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return <section className="border-t-2 border-ink px-4 py-12 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto max-w-4xl"><p className="font-black uppercase tracking-[0.18em] text-serbian-red">{number}</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">{title}</h2>{children}</div></section>;
}

export default function LessonTwoContent() {
  return <>
    <section className="bg-serbian-blue px-4 py-14 text-white sm:px-6 sm:py-20 lg:px-8"><div className="mx-auto max-w-4xl"><p className="font-black uppercase tracking-[0.2em] text-[#ffb6b9]">A1 · лекција 02</p><h1 className="mt-5 text-5xl font-black leading-[.92] sm:text-7xl">Професије.<br/><span className="text-serbian-red">Глагол бити.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/85">Говоримо ко смо и чиме се бавимо. Учимо облике: сам, си, је, смо, сте, су.</p><p className="mt-8 font-black">После лекције умем да именујем професије, представим себе и употребим глагол бити.</p></div></section>

    <Block number="01 — УВОДНО ЧИТАЊЕ" title="На пасошкој контроли"><div className="mt-7 grid gap-4 md:grid-cols-2"><article className="border-2 border-ink bg-white p-5 shadow-comic"><h3 className="text-xl font-black">Пасошка контрола</h3><p className="mt-4 leading-8">— Добро јутро!<br/>— Добро јутро! Ваш пасош, молим.<br/>— Изволите.<br/>— Ви сте господин Бонд?<br/>— Да, ја сам Стив Бонд.<br/>— Ви сте туриста?<br/>— Не, ја сам бизнисмен.<br/>— Ваша адреса у Београду?<br/>— Хотел „Метропол“.<br/>— Изволите пасош.<br/>— Хвала.</p></article><article className="border-2 border-ink bg-white p-5 shadow-comic"><h3 className="text-xl font-black">Сусрет <span className="font-normal text-serbian-red">— встреча</span></h3><p className="mt-4 leading-8">— Извините, да ли сте ви господин Бонд?<br/>— Да, ја сам Стив Бонд.<br/>— Ја сам Љиљана Јовановић.<br/>— Драго ми је.<br/>— Ви сте Енглез?<br/>— Да, ја сам Енглез.<br/>— Добро говорите српски!<br/>— Хвала.</p></article></div></Block>

    <Block number="02 — НОВИ ВОКАБУЛАР" title="Данас учимо о професијама!"><p className="mt-5 text-lg">Danas učimo o profesijama! Обрати пажњу како се граде називи у женском роду.</p><div className="mt-7 grid gap-2 sm:grid-cols-2 md:grid-cols-3">{professions.map((item, index) => <div key={item} className="border-2 border-ink bg-white p-3 font-bold"><span className="mr-2 text-xs text-serbian-red">{String(index + 1).padStart(2, "0")}</span>{item}</div>)}</div><div className="mt-6 border-l-8 border-serbian-red bg-white p-5"><b>Погодите, шта значе речи:</b><p className="mt-2 leading-7">таксиста, адвокат, дипломата, пилот, пекар, судија, контролор, директор, фотограф, возач, чувар, рачуновођа, музичар, астронаут, инфлуенсер?</p></div></Block>

    <Block number="03 — СТРИП" title="Ana, konj u velikom gradu!"><p className="mt-5 leading-7 text-ink/70">Оригинални стрип из лекције будет добавлен сюда кадр за кадром, в том же порядке, что и в Gamma.</p></Block>

    <Block number="04 — ГРАМАТИКА" title="Глагол ЈЕСАМ (бити)"><p className="mt-5 max-w-3xl text-lg leading-8">У српском језику глагол <b>БИТИ</b> («быть») је обавезан. Без њега нема ни садашњег ни прошлог времена — у томе је једна од кључних разлика између српског и руског.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="border-2 border-ink bg-white p-4"><b>С именицей</b><p className="mt-2">Ја сам студент. <span className="text-ink/55">— Я студент.</span></p></div><div className="border-2 border-ink bg-white p-4"><b>С прилагательным</b><p className="mt-2">Она је лепа. <span className="text-ink/55">— Она красивая.</span></p></div><div className="border-2 border-ink bg-white p-4"><b>С местом</b><p className="mt-2">Ми смо код куће. <span className="text-ink/55">— Мы дома.</span></p></div><div className="border-2 border-ink bg-white p-4"><b>С состоянием</b><p className="mt-2">Ја сам гладна. <span className="text-ink/55">— Я голодна.</span></p></div></div><div className="mt-6 grid grid-cols-3 border-2 border-ink bg-white text-center sm:grid-cols-6">{[["Ја","сам"],["Ти","си"],["Он / Она / Оно","је"],["Ми","смо"],["Ви","сте"],["Они / Оне / Она","су"]].map(([person, form]) => <div key={form} className="border-b-2 border-r-2 border-ink p-3 last:border-r-0 sm:border-b-0"><p className="text-sm">{person}</p><b className="text-2xl text-serbian-red">{form}</b></div>)}</div></Block>

    <Block number="05 — ПОРЕЂЕЊЕ" title="Упоредимо српски и руски"><div className="mt-7 grid gap-4 md:grid-cols-2"><div className="border-2 border-ink bg-white p-5"><h3 className="font-black">Руски</h3><p className="mt-3 text-lg leading-8">Я студент.<br/>Она дома.<br/>Мы умнейшие.</p></div><div className="border-2 border-ink bg-serbian-blue p-5 text-white"><h3 className="font-black">Српски</h3><p className="mt-3 text-lg leading-8">Ја <b className="text-[#ffb6b9]">САМ</b> студент.<br/>Она <b className="text-[#ffb6b9]">ЈЕ</b> код куће.<br/>Ми <b className="text-[#ffb6b9]">СМО</b> најпаметнији.</p></div></div><div className="mt-5 border-2 border-ink bg-white p-5"><b>Показна заменица + БИТИ + именица</b><p className="mt-3 leading-8">Ово <span className="font-black text-serbian-red">ЈЕ</span> кућа.<br/>То <span className="font-black text-serbian-red">ЈЕ</span> мој брат.<br/>Оно <span className="font-black text-serbian-red">СУ</span> деца.</p></div></Block>

    <Block number="07 — БИЋЕ ТИ КОРИСНО" title="Фразе за час"><div className="mt-7 grid gap-4 md:grid-cols-2"><div className="border-2 border-ink bg-white p-5"><b>Извините…</b><p className="mt-3 leading-8">Извините, шта значи ова реч?<br/>Шта ово значи?<br/>Како се пише…? Како се чита…?</p></div><div className="border-2 border-ink bg-white p-5"><b>Објашњења</b><p className="mt-3 leading-8">Је л’ можете да поновите?<br/>Молим Вас, поновите, нисам разумео/разумела.<br/>Не разумем…</p></div><div className="border-2 border-ink bg-white p-5"><b>Како да кажем</b><p className="mt-3 leading-8">Нисам сигуран/сигурна.<br/>Професоре/Професорка…<br/>Могу ли да Вас нешто питам?</p></div><div className="border-2 border-ink bg-white p-5"><b>Је л’ говорите српски?</b><p className="mt-3 leading-8">Да, (по)мало. / Говорим (по)мало.<br/>Разумем помало. / Знам нешто.</p></div></div></Block>

    <Block number="08 — ДОМАЋИ ЗАДАТАК" title="Вежбе за код куће"><div className="mt-7 grid gap-4 md:grid-cols-2"><a className="border-2 border-ink bg-serbian-blue p-5 font-black text-white shadow-comic" href="https://learningapps.org/watch?id=pvoby9i1k26" target="_blank" rel="noreferrer">1. Нове речи ↗</a><a className="border-2 border-ink bg-serbian-red p-5 font-black text-white shadow-comic" href="https://learningapps.org/watch?id=p6pbz143t26" target="_blank" rel="noreferrer">2. Упиши глагол бити ↗</a></div></Block>
  </>;
}
