"use client";

import { useMemo, useState } from "react";
import { Check, ChevronDown, Volume2 } from "lucide-react";

const vocabulary = [["царство","царство / империя"],["цар","царь, император"],["владар","правитель"],["освојити","завоевать"],["прогласити","провозгласить"],["крунисати","короновать"],["донети закон","принять закон"],["умрети","умереть"]] as const;
const timeline = [["око 1308.","Рођен је Стефан Душан, син краља Стефана Дечанског."],["1331.","Постао је краљ Србије."],["1334–1345.","Освојио је велике делове Македоније, Епира и Тесалије."],["1346.","Крунисан је за цара Срба и Грка у Скопљу."],["1349. / 1354.","Донео је Душанов законик — један од најважнијих средњовековних правних споменика."],["1355.","Умро је изненада; после његове смрти царство је почело да се распада."]] as const;
const verbs = [["освојити","освојио","завоевать"],["постати","постао","стать"],["крунисати","крунисан","короновать"],["донети","донео","принять / принести"],["умрети","умро","умереть"]] as const;

export default function LessonSeventeenExperience() {
  const [open, setOpen] = useState<number | null>(null);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [checked, setChecked] = useState(false);
  const [done, setDone] = useState(false);
  const questions = useMemo<Array<[string,string,string[]]>>(() => [
    ["Душан ___ краљ Србије 1331. године.","постао је",["постао је","постаје","постаћу"]],
    ["Он ___ за цара 1346. године.","крунисан је",["крунисан је","крунише","крунисао"]],
    ["Цар ___ Душанов законик.","донео је",["доноси","донео је","донеће"]],
    ["После његове смрти царство ___ да се распада.","је почело",["је почело","почиње","ће почети"]],
  ], []);
  const score = questions.filter(([, correct], index) => answers[String(index)] === correct).length;
  return <main id="lesson-17-start" className="bg-[#f8f1e7] px-4 py-10 sm:px-6 sm:py-16"><div className="mx-auto max-w-4xl">
    <div className="border-2 border-ink bg-serbian-blue p-6 text-white shadow-[7px_7px_0_#e83d34] sm:p-10"><p className="font-black uppercase tracking-[.18em] text-[#ffd55c]">istorija + gramatika</p><h2 className="mt-3 text-4xl font-black leading-tight sm:text-6xl">Dušanovo carstvo</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/85">Учимся говорить о прошлом через историю Сербии: читаем, слышим и используем перфекат.</p><a href="#istorija" className="mt-7 inline-flex rounded-full bg-serbian-red px-6 py-3 font-black shadow-[3px_3px_0_#202124]">Počinjemo ↓</a></div>
    <section id="istorija" className="scroll-mt-20 pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">1. priča</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Ко је био цар Душан?</h2><div className="mt-5 border-2 border-ink bg-white p-5 leading-8 shadow-comic sm:p-7"><p><strong>Стефан Урош IV Душан</strong>, познат као <strong>цар Душан</strong>, био је српски средњовековни владар. Постао је краљ Србије 1331. године. За време његове владавине Србија је постала највећа и најмоћнија држава на Балкану.</p><p className="mt-4">Душан је освојио велике територије на југу Балкана. Године 1346. у Скопљу је крунисан за <strong>цара Срба и Грка</strong>. Он је желео да направи снажну државу са јасним законима.</p><p className="mt-4">Године 1349. донео је <strong>Душанов законик</strong>; допуњен је 1354. године. Законик је уређивао живот у држави: судове, обавезе властеле, градове, села и цркву. Душан је умро 1355. године. После његове смрти царство је почело да се распада.</p></div><button type="button" className="mt-4 inline-flex items-center gap-2 rounded-lg border-2 border-ink bg-white px-4 py-3 font-black shadow-[3px_3px_0_#202124]" onClick={() => window.speechSynthesis?.speak(new SpeechSynthesisUtterance("Stefan Dušan je bio srpski srednjovekovni vladar."))}><Volume2 size={18} /> Слушать пример</button></section>
    <section className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">2. vremenska linija</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Шесть ключевых дат</h2><div className="mt-5 space-y-3">{timeline.map(([date,text], index) => <button type="button" key={date} onClick={() => setOpen(open===index?null:index)} className="w-full border-2 border-ink bg-white p-4 text-left shadow-[3px_3px_0_#202124]"><div className="flex items-center justify-between gap-4"><span className="font-black text-serbian-red">{date}</span><ChevronDown className={open===index?"rotate-180 transition":"transition"} /></div>{open===index?<p className="mt-3 leading-7">{text}</p>:<p className="mt-1 text-sm text-ink/65">Нажми, чтобы открыть событие</p>}</button>)}</div></section>
    <section className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">3. nove reči</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Историческая лексика</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{vocabulary.map(([word,translation])=><div key={word} className="border-2 border-ink bg-white p-4 shadow-[3px_3px_0_#202124]"><p className="text-xl font-black">{word}</p><p className="mt-1 text-ink/70">{translation}</p></div>)}</div></section>
    <section className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">4. gramatika</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Перфекат: что произошло?</h2><div className="mt-5 border-2 border-ink bg-[#fff7d6] p-5 leading-7 shadow-comic"><p><strong>Перфекат</strong> нужен, когда мы говорим о завершённом действии в прошлом.</p><p className="mt-2 font-black">Он: је + радни глаголски придев</p><p>Душан <strong>је освојио</strong> територије. Он <strong>је донео</strong> законик.</p><p className="mt-2 font-black">Пассивная форма:</p><p>Душан <strong>је крунисан</strong> за цара. = Душана короновали как царя.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{verbs.map(([i,p,t])=><div key={i} className="border-2 border-ink bg-white p-4"><p className="font-black">{i}</p><p className="mt-2 text-xl font-black text-serbian-red">он је {p}</p><p className="mt-1 text-sm text-ink/65">{t}</p></div>)}</div></section>
    <section className="pt-14"><p className="font-black uppercase tracking-[.16em] text-serbian-red">5. proveri se</p><h2 className="mt-2 text-3xl font-black text-serbian-blue">Выбери правильную форму</h2><div className="mt-5 space-y-4">{questions.map(([prompt,correct,options],index)=><div key={prompt} className="border-2 border-ink bg-white p-5 shadow-comic"><p className="font-black">{index+1}. {prompt}</p><div className="mt-3 flex flex-wrap gap-2">{options.map(option=><button type="button" key={option} onClick={()=>{setAnswers(old=>({...old,[index]:option}));setChecked(false)}} className={"rounded-lg border-2 border-ink px-4 py-2 font-bold "+(answers[String(index)]===option?"bg-serbian-blue text-white":"bg-white")}>{option}</button>)}</div>{checked&&answers[String(index)]?<p className={"mt-3 font-black "+(answers[String(index)]===correct?"text-green-700":"text-serbian-red")}>{answers[String(index)]===correct?"Тачно!":"Тачан одговор: "+correct}</p>:null}</div>)}</div><button type="button" onClick={()=>setChecked(true)} className="mt-5 rounded-lg border-2 border-ink bg-serbian-red px-5 py-3 font-black text-white shadow-[3px_3px_0_#202124]">Проверить</button>{checked?<div className="mt-4 border-2 border-ink bg-white p-4 font-black">Твой результат: {score} / {questions.length}</div>:null}</section>
    <section className="mt-14 border-2 border-ink bg-serbian-blue p-6 text-white shadow-[7px_7px_0_#e83d34] sm:p-8"><p className="font-black uppercase tracking-[.16em] text-[#ffd55c]">domaći zadatak</p><h2 className="mt-2 text-3xl font-black">Напиши мини-историю</h2><ol className="mt-4 list-decimal space-y-2 pl-6 leading-7"><li>Напиши 4–5 предложений о царе Душане, используя минимум три глагола в перфекате.</li><li>Ответь: <em>Шта је Душан освојио? Када је крунисан? Шта је донео?</em></li><li>Прочитай текст вслух и отправь преподавателю.</li></ol><button type="button" onClick={()=>setDone(true)} className="mt-6 inline-flex items-center gap-2 rounded-lg border-2 border-ink bg-white px-5 py-3 font-black text-serbian-blue shadow-[3px_3px_0_#202124]"><Check size={18} /> Завершить урок</button>{done?<p className="mt-5 rounded-lg bg-white/15 p-4 text-xl font-black">Браво! Сада можеш да причаш о Душановом царству. 🎉</p>:null}</section>
  </div></main>;
}