const sections = [
  ['Комикс','План, который съел Мачкослав','Полина, Маша, Коцкослав и Мачкослав собираются на Ртань.'],
  ['Грамматика','Будущее время с ЋЕ','Планы, обещания и вопросы в будущем времени.'],
  ['Новые слова','Слова из комикса','Соедини слово и перевод.'],
  ['Практика','Выбери и дополни','Выбери форму будущего времени.'],
  ['Чтение','Планы Полины на выходные','Прочитай и найди формы будущего времени.'],
  ['Понимание','Вопросы по тексту','Ответь на вопросы и проверь понимание.'],
  ['Преобразования','Из настоящего в будущее','Утверждение, отрицание и вопрос.'],
  ['Мой план','Мои планы на выходные','Расскажи о своих планах.'],
  ['Домашнее задание','Что я буду делать в выходные?','Напиши 7–8 предложений.']
];
const sectionAudioTracks = [null, null, null, null, null, null, null, null, null];
const comic = [
  ['План за викенд',[['Полина','За викенд ћемо ићи на Ртањ!','В выходные мы поедем на Ртань!'],['Маша','Ја ћу направити сендвиче.','Я приготовлю бутерброды.'],['Мачкослав','А ја ћу контролисати сендвиче.','А я буду контролировать бутерброды.']]],
  ['Ко ће шта понети?',[['Полина','Маша ће понети воду.','Маша возьмёт воду.'],['Коцкослав','Ја ћу припремити мапу и маршрут!','Я подготовлю карту и маршрут!'],['Полина','Каже се рута.','Говорят «рута».']]],
  ['Полазимо веома рано',[['Полина','Наћи ћемо се у пола шест.','Встретимся в половине шестого.'],['Мачкослав','Ја нећу устати тако рано!','Я не встану так рано!'],['Маша','Хоћеш. Позваћу те у пет.','Встанешь. Я позвоню тебе в пять.']]],
  ['Како ће изгледати планинарење?',[['Полина','Пре подне ћемо се попети на планину.','До полудня мы поднимемся на гору.'],['Маша','Фотографисаћу природу.','Я буду фотографировать природу.'],['Мачкослав','А ко ће носити мене?','А кто понесёт меня?']]],
  ['План за недељу',[['Полина','После планинарења ћемо отићи у хотел.','После похода мы пойдём в гостиницу.'],['Маша','Посетићемо пијацу.','Мы посетим рынок.'],['Мачкослав','Не заборавите палачинке.','Не забудьте блины.']]],
  ['Велико обећање',[['Маша','Да ли ћеш чувати сендвиче?','Ты будешь охранять бутерброды?'],['Мачкослав','Хоћу! Нећу појести ниједан.','Буду! Не съем ни одного.'],['Полина','Сигурно?','Точно?']]],
  ['Пет сати ујутру',[['Маша','Где су сендвичи?','Где бутерброды?'],['Мачкослав','Можда су отишли на Ртањ без нас.','Может, они отправились на Ртань без нас.'],['Полина','Мачкославе!','Мачкослав!']]],
  ['Ипак крећемо!',[['Полина','Купићемо храну успут.','Купим еду по дороге.'],['Коцкослав','Ово ће бити најбољи викенд!','Это будут лучшие выходные!'],['Мачкослав','Следећи пут ћу бити одговорнији.','В следующий раз я буду ответственнее.']]]
];
let current=0, frame=0, translated=false, chapter=0, builderMode='positive';
let saved={completed:[],answers:{},drafts:{},reading:[],finished:false};
try {saved={...saved,...JSON.parse(localStorage.getItem('tyserb-lesson18')||'{}')};}catch{}
if(Number.isInteger(saved.current)&&saved.current>=0&&saved.current<9)current=saved.current;
const activity=document.querySelector('#activity');
document.body.classList.toggle('embedded', window.self !== window.top);
function renderSectionAudio(){const player=document.querySelector('#section-audio-player');if(player.dataset.section===String(current))return;player.pause();player.dataset.section=String(current);const source=sectionAudioTracks[current];document.querySelector('#audio-title').textContent=`Аудио · ${current+1}. ${sections[current][0]}`;document.querySelector('#audio-status').textContent=source?'':'Запись готовится';player.removeAttribute('src');if(source)player.src=source;player.load();}
document.querySelector('#section-audio-player').addEventListener('error',()=>{document.querySelector('#audio-status').textContent='Запись временно недоступна';});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){saved.current=current;updateProgress();try{localStorage.setItem('tyserb-lesson18',JSON.stringify(saved));document.querySelector('#save-status').textContent='Прогресс сохранён на этом устройстве.';}catch{document.querySelector('#save-status').textContent='Прогресс доступен до закрытия страницы.';}}
function icons(){window.lucide?.createIcons();}
function render(){document.querySelector('#section-kicker').textContent=`${current+1}. ${sections[current][0].toUpperCase()}`;document.querySelector('#section-title').textContent=sections[current][1];document.querySelector('#section-description').textContent=sections[current][2];document.querySelector('#steps').innerHTML=sections.map((s,i)=>`<button class="step ${i===current?'active':''} ${saved.completed.includes(i)?'complete':''}" data-step="${i}" aria-label="Раздел ${i+1}: ${s[0]}" title="${i+1}. ${s[0]}" ${i===current?'aria-current="step"':''}></button>`).join('');document.querySelector('#progress-count').textContent=`${saved.completed.length}/9`;document.querySelector('#step-caption').textContent=`${current+1} из 9`;document.querySelector('#previous').disabled=current===0;document.querySelector('#next').textContent=current===8?'Завершить урок':'Дальше';renderSectionAudio();renderActivity();icons();persist();}
function renderComic(){const c=comic[frame];activity.innerHTML=`<div class="comic-layout"><div><img class="comic-image" src="assets/slide-${frame+2}-1.png" alt="Комикс: ${esc(c[0])}" width="600" height="600"><div class="comic-controls"><button class="icon-button" id="comic-prev" aria-label="Предыдущий кадр" ${frame===0?'disabled':''}><i data-lucide="chevron-left"></i></button><div class="comic-dots">${comic.map((_,i)=>`<button data-frame="${i}" class="${i===frame?'active':''}" aria-label="Кадр ${i+1}" ${i===frame?'aria-current="true"':''}></button>`).join('')}</div><button class="icon-button" id="comic-next" aria-label="Следующий кадр" ${frame===7?'disabled':''}><i data-lucide="chevron-right"></i></button></div></div><div><p class="comic-number">КОМИКС · КАДР ${frame+1}/8</p><h3>${esc(c[0])}</h3>${c[1].map(l=>`<div class="dialogue"><div class="speaker">${l[0]}</div><p lang="sr">«${l[1]}»</p>${translated?`<p class="translation">${l[2]}</p>`:''}</div>`).join('')}<button id="translation" class="text-button" aria-expanded="${translated}">${translated?'Скрыть перевод':'Показать перевод'}</button></div></div><div class="note">${frame===7?'Следећи пут ћу бити одговорнији. <strong>Ћу бити</strong> — «буду».': '<strong>За викенд ћемо ићи на Ртањ.</strong><br>Ћемо ићи — «мы поедем». Действие произойдёт в будущем.'}</div>`;icons();}
const people=['ја','ти','он / она','ми','ви','они / оне'];
const auxiliaries=['ћу','ћеш','ће','ћемо','ћете','ће'];
const negatives=['нећу','нећеш','неће','нећемо','нећете','неће'];
const vocab=[['планина','гора'],['планинарење','поход в горы'],['рута','маршрут'],['опрема','снаряжение'],['понети','взять с собой'],['чувати','охранять']];
const choiceRows=[
 {prompt:'Ја ___ понети воду.',options:['ћу','ће'],answer:'ћу'},
 {prompt:'Маша ___ направити сендвиче.',options:['ћеш','ће'],answer:'ће'},
 {prompt:'Ми ___ ићи на Ртањ.',options:['ћемо','ће'],answer:'ћемо'},
 {prompt:'Ти ___ понети фотоапарат.',options:['ћеш','ћемо'],answer:'ћеш'},
 {prompt:'Коцкослав ___ носити опрему.',options:['ћу','ће'],answer:'ће'},
 {prompt:'Они ___ путовати аутобусом.',options:['ћете','ће'],answer:'ће'}
];
const fillRows=[
 {prompt:'Ја ___ читати књигу.',answer:'ћу'},
 {prompt:'Ти ___ понети воду.',answer:'ћеш'},
 {prompt:'Маша ___ направити сендвиче.',answer:'ће'},
 {prompt:'Ми ___ ићи на планину.',answer:'ћемо'},
 {prompt:'Ви ___ спавати у хотелу.',answer:'ћете'},
 {prompt:'Полина и Маша ___ купити храну.',answer:'ће'}
];
const readingChapters=[
  [
    'Следећег викенда Полина <f>ће ићи</f> на Ртањ са Машом, Коцкославом и Мачкославом. Они <f>ће поћи</f> у суботу рано ујутру.',
    'Полина <f>ће устати</f> у пет сати. Она <f>ће проверити</f> карте и <f>позваће</f> Машу. Маша <f>ће направити</f> сендвиче и <f>понеће</f> воду.'
  ],
  [
    'Коцкослав <f>ће припремити</f> мапу и <f>носиће</f> велики ранац. Мачкослав <f>неће понети</f> опрему. Он каже да <f>ће чувати</f> храну, али му нико не верује.',
    'Аутобус <f>ће поћи</f> у шест. На Ртњу пријатељи <f>ће се попети</f> на планину. Маша <f>ће фотографисати</f> природу, а Коцкослав <f>ће тражити</f> лековито биље.'
  ],
  [
    'После планинарења они <f>ће отићи</f> у мали хотел. Тамо <f>ће вечерати</f> и <f>спаваће</f> једну ноћ. У недељу <f>ће посетити</f> пијацу и <f>купиће</f> воће, поврће и нове сендвиче.',
    'После ручка <f>ће се вратити</f> кући. Мачкослав каже да следећи пут <f>неће појести</f> све сендвиче. Нико му не верује.'
  ]
];
const comprehensionRows=[
 {prompt:'Где ће Полина ићи за викенд?',answer:'Полина ће ићи на Ртањ.',keys:[['rtanj']]},
 {prompt:'С ким ће ићи?',answer:'Ићи ће са Машом, Коцкославом и Мачкославом.',keys:[['masom'],['kockoslavom'],['mackoslavom']]},
 {prompt:'Када ће поћи?',answer:'Они ће поћи у суботу рано ујутру.',keys:[['subotu'],['ujutru','rano']]},
 {prompt:'Ко ће направити сендвиче?',answer:'Маша ће направити сендвиче.',keys:[['masa'],['sendvice']]},
 {prompt:'Шта ће понети Маша?',answer:'Маша ће понети воду.',keys:[['vodu']]},
 {prompt:'Ко ће припремити мапу?',answer:'Коцкослав ће припремити мапу.',keys:[['kockoslav'],['mapu']]},
 {prompt:'Да ли ће Мачкослав понети опрему?',answer:'Не, Мачкослав неће понети опрему.',keys:[['nece'],['opremu']],negative:true},
 {prompt:'У колико сати ће поћи аутобус?',answer:'Аутобус ће поћи у шест сати.',keys:[['sest','6']]},
 {prompt:'Шта ће Маша фотографисати?',answer:'Маша ће фотографисати природу.',keys:[['prirodu']]},
 {prompt:'Где ће пријатељи спавати?',answer:'Пријатељи ће спавати у малом хотелу.',keys:[['hotelu']]},
 {prompt:'Шта ће купити на пијаци?',answer:'Купиће воће, поврће и нове сендвиче.',keys:[['voce'],['povrce'],['sendvice']]},
 {prompt:'Када ће се вратити кући?',answer:'Вратиће се кући после ручка.',keys:[['posle rucka']]},
 {prompt:'Шта Мачкослав неће појести?',answer:'Мачкослав неће појести све сендвиче.',keys:[['nece'],['sendvice']],negative:true}
];
const truthRows=[
 {prompt:'Полина ће ићи на Ртањ.',options:['Тачно','Нетачно'],answer:'Тачно'},
 {prompt:'Они ће поћи у понедељак.',options:['Тачно','Нетачно'],answer:'Нетачно',hint:'Они ће поћи у суботу рано ујутру.'},
 {prompt:'Маша ће направити сендвиче.',options:['Тачно','Нетачно'],answer:'Тачно'},
 {prompt:'Мачкослав ће носити велики ранац.',options:['Тачно','Нетачно'],answer:'Нетачно',hint:'Коцкослав ће носити велики ранац.'},
 {prompt:'Аутобус ће поћи у шест.',options:['Тачно','Нетачно'],answer:'Тачно'},
 {prompt:'Они ће спавати у шатору.',options:['Тачно','Нетачно'],answer:'Нетачно',hint:'Они ће спавати у малом хотелу.'},
 {prompt:'У недељу ће посетити пијацу.',options:['Тачно','Нетачно'],answer:'Тачно'}
];
const presentRows=[
 {prompt:'Маша прави сендвиче.',answer:'Маша ће правити сендвиче.',alternatives:['Маша ће да прави сендвиче.']},
 {prompt:'Полина проверава карте.',answer:'Полина ће проверавати карте.',alternatives:['Полина ће да проверава карте.']},
 {prompt:'Коцкослав носи ранац.',answer:'Коцкослав ће носити ранац.',alternatives:['Коцкослав ће да носи ранац.']},
 {prompt:'Мачкослав чува храну.',answer:'Мачкослав ће чувати храну.',alternatives:['Мачкослав ће да чува храну.']},
 {prompt:'Они иду на Ртањ.',answer:'Они ће ићи на Ртањ.',alternatives:['Ићи ће на Ртањ.','Они ће да иду на Ртањ.']},
 {prompt:'Аутобус полази у шест.',answer:'Аутобус ће полазити у шест.',alternatives:['Аутобус ће да полази у шест.']}
];
const negativeRows=[
 {prompt:'Маша ће заборавити воду.',answer:'Маша неће заборавити воду.',alternatives:['Маша неће да заборави воду.']},
 {prompt:'Ми ћемо остати код куће.',answer:'Ми нећемо остати код куће.',alternatives:['Нећемо остати код куће.','Ми нећемо да останемо код куће.']},
 {prompt:'Полина ће закаснити.',answer:'Полина неће закаснити.',alternatives:['Полина неће да закасни.']},
 {prompt:'Коцкослав ће изгубити мапу.',answer:'Коцкослав неће изгубити мапу.',alternatives:['Коцкослав неће да изгуби мапу.']},
 {prompt:'Они ће се вратити рано.',answer:'Они се неће вратити рано.',alternatives:['Они неће да се врате рано.','Неће се вратити рано.']},
 {prompt:'Мачкослав ће понети опрему.',answer:'Мачкослав неће понети опрему.',alternatives:['Мачкослав неће да понесе опрему.']}
];
const questionRows=[
 {prompt:'Полина ће ићи на Ртањ.',answer:'Да ли ће Полина ићи на Ртањ?',alternatives:['Хоће ли Полина ићи на Ртањ?']},
 {prompt:'Коцкослав ће понети мапу.',answer:'Да ли ће Коцкослав понети мапу?',alternatives:['Хоће ли Коцкослав понети мапу?']},
 {prompt:'Они ће путовати аутобусом.',answer:'Да ли ће они путовати аутобусом?',alternatives:['Хоће ли они путовати аутобусом?']},
 {prompt:'Мачкослав ће чувати храну.',answer:'Да ли ће Мачкослав чувати храну?',alternatives:['Хоће ли Мачкослав чувати храну?']},
 {prompt:'Пријатељи ће спавати у хотелу.',answer:'Да ли ће пријатељи спавати у хотелу?',alternatives:['Хоће ли пријатељи спавати у хотелу?']}
];
const tasks={choice:{title:'Упражнение 1 · Выбери правильную форму',description:'Выбери форму глагола ХТЕТИ.',rows:choiceRows,type:'choice'},fill:{title:'Упражнение 2 · Дополни предложения',description:'Впиши: ћу · ћеш · ће · ћемо · ћете · ће',rows:fillRows,type:'short'},comprehension:{title:'Ответь полным предложением',description:'Пиши по-сербски на кириллице. Используй будущее время.',rows:comprehensionRows,type:'text'},truth:{title:'Верно или неверно?',description:'Если утверждение неверно, сравни его с исправлением.',rows:truthRows,type:'choice'},present:{title:'Упражнение 3 · Из настоящего в будущее',description:'Маша прави → Маша ће правити',rows:presentRows,type:'text'},negative:{title:'Упражнение 4 · Сделай отрицание',description:'Ићи ћу. → Нећу ићи.',rows:negativeRows,type:'text'},questions:{title:'Упражнение 5 · Составь вопрос',description:'Маша ће доћи. → Да ли ће Маша доћи?',rows:questionRows,type:'text'}};
const translit={'а':'a','б':'b','в':'v','г':'g','д':'d','ђ':'đ','е':'e','ж':'ž','з':'z','и':'i','ј':'j','к':'k','л':'l','љ':'lj','м':'m','н':'n','њ':'nj','о':'o','п':'p','р':'r','с':'s','т':'t','ћ':'ć','у':'u','ф':'f','х':'h','ц':'c','ч':'č','џ':'dž','ш':'š'};
function latin(s){return String(s).toLowerCase().replace(/[а-яђјљњћџ]/g,c=>translit[c]||c);}
function normalize(s){return latin(s).replace(/đ/g,'dj').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();}
function futureUsed(s){const t=normalize(s);return /\b(necu|neces|nece|necemo|necete|cu|ces|ce|cemo|cete)\b/.test(t)||/\b[a-z]+c(u|es|emo|ete)\b/.test(t)||/\b(cita|gleda|kupi|napravi|pravi|proveri|proverava|pozva|pone|nosi|cuva|pripremi|fotografisa|trazi|vecera|spava|poseti|vrati|pojede|uce|uci|putova|polazi|osta)ce\b/.test(t);}
function correctAnswer(value,row){const v=normalize(value);if(!v)return false;if([row.answer,...(row.alternatives||[])].some(a=>normalize(a)===v))return true;if(row.keys){const isNegative=/\bne(cu|ces|ce|cemo|cete)\b/.test(v);return isNegative===Boolean(row.negative)&&futureUsed(value)&&row.keys.every(group=>group.some(k=>v.includes(k)))&&v.split(' ').length>=4;}return false;}
function answerRecord(key){return saved.answers[key]||{value:'',status:''};}
function feedback(key,row){const a=answerRecord(key);if(!a.status)return '';const message=a.status==='correct'?'Верно!'+(row.hint?' '+row.hint:''):a.status==='wrong'?'Пока неверно. Попробуй ещё раз.':'Пример ответа: '+row.answer;return `<p class="feedback ${a.status}" role="status">${esc(message)}</p>`;}
function renderTask(id){const t=tasks[id];const correct=t.rows.filter((_,i)=>answerRecord(`${id}-${i}`).status==='correct').length;return `<div class="task" data-task="${id}"><h3>${t.title}</h3><p class="task-description">${t.description}</p>${t.rows.map((r,i)=>{const key=`${id}-${i}`,a=answerRecord(key);return `<div class="question ${t.type==='short'?'short':''} ${a.status}" id="row-${key}"><div class="question-prompt"><span class="q-number">${i+1}</span><span id="label-${key}" lang="sr">${esc(r.prompt)}</span></div>${t.type==='choice'?`<div class="answers" role="radiogroup" aria-labelledby="label-${key}">${r.options.map(o=>`<label class="choice"><input type="radio" name="${key}" data-answer="${key}" value="${esc(o)}" ${a.value===o?'checked':''}><span lang="sr">${esc(o)}</span></label>`).join('')}</div>`:`<input type="text" data-answer="${key}" value="${esc(a.value)}" aria-labelledby="label-${key}" placeholder="${t.type==='short'?'…':'Твой ответ на сербском'}" spellcheck="false" autocomplete="off">`}${feedback(key,r)}</div>`}).join('')}<div class="task-actions"><button class="button secondary" data-check="${id}"><i data-lucide="check"></i>Проверить</button><button class="text-button" data-reveal="${id}">Показать ответы</button><button class="text-button" data-retry="${id}">Ещё раз</button><p class="task-summary" aria-live="polite">${correct} из ${t.rows.length} верно</p></div></div>`;}
function renderGrammar(){return `<table class="grammar-table"><thead><tr><th>ЛИЦО</th><th>УТВЕРЖДЕНИЕ</th><th>ОТРИЦАНИЕ</th></tr></thead><tbody>${people.map((p,i)=>`<tr><td lang="sr">${p}</td><td>${auxiliaries[i]}</td><td>${negatives[i]}</td></tr>`).join('')}</tbody></table><div class="note" lang="sr">Ја <strong>ћу читати.</strong> · Ми <strong>ћемо ићи.</strong> · Они <strong>неће остати.</strong></div><div class="subsection"><h3>Три формы, одно значение</h3><div class="models"><div class="model"><strong lang="sr">Ја ћу читати.</strong><span>ћу + инфинитив</span></div><div class="model"><strong lang="sr">Читаћу.</strong><span>Слитная форма</span></div><div class="model"><strong lang="sr">Ја ћу да читам.</strong><span>ћу + да + презент</span></div></div><p lang="sr">Сутра ћу учити. = Сутра ћу да учим. = Учићу сутра.</p></div><div class="two-columns subsection"><div class="rule"><h3>Глаголы на -ТИ</h3><p lang="sr">читати → <strong>читаћу</strong></p><p lang="sr">гледати → <strong>гледаћу</strong></p><p lang="sr">купити → <strong>купићу</strong></p><p lang="sr">направити → <strong>направићу</strong></p><p>Отбрасываем -ти и добавляем ћу, ћеш, ће…</p></div><div class="rule"><h3>Глаголы на -ЋИ</h3><p lang="sr">ићи → <strong>ићи ћу</strong></p><p lang="sr">доћи → <strong>доћи ћу</strong></p><p lang="sr">поћи → <strong>поћи ћу</strong></p><p lang="sr">наћи → <strong>наћи ћу</strong></p><p>Инфинитив и краткая форма пишутся раздельно.</p></div></div><div class="note"><strong>Доћи ћу.</strong> Написание «доћићу» неверно.</div><div class="builder"><h3>Составь предложение</h3><div class="builder-controls"><label><span class="field-label">Лицо</span><select id="builder-person">${people.map((p,i)=>`<option value="${i}">${p}</option>`).join('')}</select></label><label><span class="field-label">Глагол</span><select id="builder-verb"><option>читати</option><option>гледати</option><option>купити</option><option>направити</option><option>ићи</option><option>доћи</option><option>поћи</option><option>наћи</option></select></label></div><div class="segmented" aria-label="Форма предложения">${[['positive','Утверждение'],['negative','Отрицание'],['question','Вопрос']].map(([v,l])=>`<button data-mode="${v}" aria-pressed="${v===builderMode}">${l}</button>`).join('')}</div><p id="builder-result" class="builder-result" lang="sr" aria-live="polite"></p><p id="builder-alternative" lang="sr"></p></div><div class="subsection"><h3>Как задавать вопросы и отвечать?</h3><p lang="sr"><strong>Да ли ћеш доћи?</strong></p><div class="two-columns"><div class="rule"><strong lang="sr">Да, хоћу.</strong><p lang="sr">Доћи ћу.</p></div><div class="rule"><strong lang="sr">Не, нећу.</strong><p lang="sr">Нећу доћи.</p></div></div><p lang="sr">Да ли ћете ићи на Ртањ? — Да, хоћемо! Ићи ћемо!</p><p lang="sr">Да ли ће они спавати у хотелу? — Да, хоће. Спаваће.</p></div>`;}
function updateBuilder(){const p=Number(document.querySelector('#builder-person')?.value||0);const verb=document.querySelector('#builder-verb')?.value||'читати';const who=people[p].split(' / ')[0];let text='',alternative='';if(builderMode==='positive'){text=`${who[0].toUpperCase()+who.slice(1)} ${auxiliaries[p]} ${verb}.`;alternative=verb.endsWith('ти')?`${verb.slice(0,-2)}${auxiliaries[p]}.`:`${verb} ${auxiliaries[p]}.`;alternative=alternative[0].toUpperCase()+alternative.slice(1);}if(builderMode==='negative')text=`${who[0].toUpperCase()+who.slice(1)} ${negatives[p]} ${verb}.`;if(builderMode==='question')text=`Да ли ${auxiliaries[p]} ${who} ${verb}?`;document.querySelector('#builder-result').textContent=text;document.querySelector('#builder-alternative').textContent=alternative;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===builderMode));}
function renderVocab(){const options=['взять с собой','маршрут','гора','снаряжение','охранять','поход в горы'];return `<div class="matching-grid">${vocab.map(([word,answer],i)=>{const key=`vocab-${i}`,a=answerRecord(key);return `<div class="match-row ${a.status}"><label for="${key}" class="match-word" lang="sr">${i+1}. ${word}</label><select id="${key}" data-answer="${key}"><option value="">Выбери перевод</option>${options.map(v=>`<option ${v===a.value?'selected':''}>${v}</option>`).join('')}</select></div>`}).join('')}</div><div class="task-actions"><button class="button secondary" data-check="vocab"><i data-lucide="check"></i>Проверить</button><button class="text-button" data-reveal="vocab">Показать ответы</button><button class="text-button" data-retry="vocab">Ещё раз</button><p class="task-summary" aria-live="polite">${vocab.filter((_,i)=>answerRecord(`vocab-${i}`).status==='correct').length} из 6 верно</p></div>${vocab.some((_,i)=>answerRecord(`vocab-${i}`).status==='wrong')?'<p class="live-note" role="status">Проверь пары, отмеченные красным.</p>':''}<div class="subsection"><h3>Используем новые слова</h3><p lang="sr">Маша ће <strong>понети</strong> воду. Коцкослав ће припремити <strong>руту</strong>. Мачкослав ће <strong>чувати</strong> храну.</p><img class="reading-image" src="assets/slide-3-1.png" alt="Друзья готовят карту для похода" width="800" height="450" loading="lazy"></div>`;}
function renderReading(){let n=0;const paragraphs=readingChapters[chapter].map(p=>`<p>${p.replace(/<f>(.*?)<\/f>/g,(_,s)=>{const key=`${chapter}-${n++}`;return `<button class="future-word" data-future="${key}" aria-pressed="${saved.reading.includes(key)}" title="${saved.reading.includes(key)?'Форма найдена':'Выделить Футур 1'}">${s}</button>`;})}</p>`).join('');const total=readingChapters.reduce((sum,c)=>sum+c.join('').match(/<f>/g).length,0);return `<div class="reading-tabs" role="tablist" aria-label="Части текста">${['Начало','На Ртне','Конец истории'].map((s,i)=>`<button role="tab" id="reading-tab-${i}" aria-selected="${chapter===i}" aria-controls="reading-panel" data-chapter="${i}">${i+1}. ${s}</button>`).join('')}</div><div class="reading-toolbar"><span class="reading-meter" aria-live="polite">Найдено ${saved.reading.length}/${total} форм Футур 1</span><button class="text-button" id="highlight-all">${saved.reading.length===total?'Убрать выделение':'Выделить все формы'}</button></div><div class="reading-text" id="reading-panel" role="tabpanel" aria-labelledby="reading-tab-${chapter}" lang="sr">${paragraphs}</div><div class="note">${[['Ко ће устати у пет?','Ко ће направити сендвиче?'],['Шта Мачкослав неће понети?','У колико сати ће поћи аутобус?'],['Где ће спавати?','Шта ће купити на пијаци?']][chapter].map(q=>`<p lang="sr">${q}</p>`).join('')}</div><img class="reading-image" src="assets/slide-${[4,5,6][chapter]}-1.png" alt="${['Ранний подъём перед поездкой','Поход на гору Ртань','Друзья после похода'][chapter]}" loading="lazy" width="800" height="450">`;}
const planPrompts=['Где ћеш ићи?','С ким ћеш ићи?','Када ћеш поћи?','Шта ћеш понети?','Шта ћеш тамо радити?','Шта нећеш радити?'];
const recapPrompts=['Сутра ћу…','За викенд ћемо…','Маша ће…','Коцкослав неће…','Да ли ћеш…?','Следеће недеље нећу…'];
function writingField(key,label,placeholder=''){return `<div class="writing-field"><label class="writing-label" for="draft-${key}" lang="sr">${esc(label)}</label><textarea id="draft-${key}" data-draft="${key}" placeholder="${esc(placeholder)}" spellcheck="false">${esc(saved.drafts[key]||'')}</textarea></div>`;}
function renderPlan(){return `<div class="note">Расскажи в 5–6 предложениях. Используй <strong>ћу / ћемо</strong>, отрицание и хотя бы один глагол на <strong>-ћи</strong>.</div>${planPrompts.map((p,i)=>writingField(`plan-${i}`,`${i+1}. ${p}`)).join('')}<div class="task-actions"><button class="button secondary" id="review-plan"><i data-lucide="check"></i>Проверить план</button><button class="text-button" data-download="plan"><i data-lucide="download"></i>Скачать текст</button></div><p id="plan-feedback" role="status" class="live-note"></p><div class="subsection"><h3>Повторение</h3>${recapPrompts.map((p,i)=>writingField(`recap-${i}`,`${i+1}. ${p}`)).join('')}</div>`;}
function homeworkChecks(){const text=saved.drafts.homework||'';const t=normalize(text);const sentences=text.split(/[.!?\n]+/).filter(s=>normalize(s).length>0).length;return [{label:'7–8 предложений',done:sentences>=7&&sentences<=8},{label:'Форма ћу',done:/\bcu\b|\b[a-z]+cu\b/.test(t)},{label:'Форма ћемо',done:/\bcemo\b|\b[a-z]+cemo\b/.test(t)},{label:'Отрицание нећу',done:/\bnecu\b/.test(t)},{label:'Глагол на -ћи',done:/\b(ici|doci|poci|naci|otici)\b/.test(t)},{label:'Вопрос «Да ли ћеш…?»',done:/\bda li ces\b/.test(t)}];}
function renderChecklist(){return `<ul class="checklist">${homeworkChecks().map(c=>`<li class="${c.done?'done':''}"><i data-lucide="${c.done?'circle-check':'circle'}"></i>${c.label}</li>`).join('')}</ul>`;}
function renderHomework(){return `<div class="note"><p>Напиши 7–8 предложений.</p><p lang="sr">Где ћеш ићи? С ким? Шта ћеш понети и радити? Када ћеш се вратити?</p></div><label class="writing-label" for="homework">Шта ћу радити за викенд?</label><textarea class="homework" id="homework" data-draft="homework" spellcheck="false" placeholder="За викенд ћу…">${esc(saved.drafts.homework||'')}</textarea><div id="homework-checklist">${renderChecklist()}</div><div class="task-actions"><button class="button secondary" id="review-homework"><i data-lucide="check"></i>Проверить условия</button><button class="text-button" data-download="homework"><i data-lucide="download"></i>Скачать текст</button></div><p id="homework-feedback" class="live-note" role="status"></p><div class="subsection"><h3>Бонус: новый кадр</h3><p lang="sr">Шта ће Мачкослав урадити на Ртњу?</p><img class="homework-image" src="assets/slide-29-1.png" alt="Мачкослав на Ртне: придумай продолжение" width="800" height="450" loading="lazy"><div class="drawing-tools"><label for="draw-color">Цвет</label><input id="draw-color" type="color" value="#0c4076"><label for="draw-width">Толщина</label><input id="draw-width" type="range" min="2" max="16" value="4"><button class="icon-button" id="draw-undo" aria-label="Отменить последний штрих" title="Отменить"><i data-lucide="undo-2"></i></button><button class="icon-button" id="draw-clear" aria-label="Очистить рисунок" title="Очистить"><i data-lucide="eraser"></i></button><button class="icon-button" id="draw-save" aria-label="Скачать рисунок" title="Скачать рисунок"><i data-lucide="download"></i></button></div><canvas id="drawing" width="1200" height="675" aria-label="Поле для рисунка нового кадра"></canvas>${writingField('speech-1','1. Добавь реплику в будущем времени:')}${writingField('speech-2','2. Добавь вторую реплику:')}</div>${saved.finished?renderCompletion():''}`;}
function renderCompletion(){const correct=Object.values(saved.answers).filter(a=>a.status==='correct').length;return `<div class="completion" role="status"><p class="eyebrow">ОТЛИЧНО!</p><h3>Урок пройден.</h3><p class="completion-score">${saved.completed.length}/9 разделов · ${correct}/55 ответов верно</p><p lang="sr">Сада ћеш говорити о својим плановима!</p><div class="end-actions"><button class="button" data-step="1">Повторить грамматику</button><a class="button primary" href="https://ty-serb.vercel.app/lessons">К урокам</a></div></div>`;}
function renderActivity(){if(current===0)renderComic();if(current===1){activity.innerHTML=renderGrammar();updateBuilder();}if(current===2)activity.innerHTML=renderVocab();if(current===3)activity.innerHTML=renderTask('choice')+'<div class="subsection">'+renderTask('fill')+'</div>';if(current===4)activity.innerHTML=renderReading();if(current===5)activity.innerHTML=renderTask('comprehension')+'<div class="subsection">'+renderTask('truth')+'</div>';if(current===6)activity.innerHTML=renderTask('present')+'<div class="subsection">'+renderTask('negative')+'</div><div class="subsection">'+renderTask('questions')+'</div>';if(current===7)activity.innerHTML=renderPlan();if(current===8){activity.innerHTML=renderHomework();initDrawing();}icons();}
function checkTask(id,reveal=false){const rows=id==='vocab'?vocab.map(v=>({answer:v[1]})):tasks[id].rows;rows.forEach((r,i)=>{const key=`${id}-${i}`,a=answerRecord(key);saved.answers[key]={...a,status:reveal?'revealed':correctAnswer(a.value,r)?'correct':'wrong'};if(id==='vocab'&&reveal)saved.answers[key].value=r.answer;});persist();renderActivity();document.querySelector(`[data-check="${id}"]`)?.focus({preventScroll:true});}
function taskComplete(id){const rows=id==='vocab'?vocab:tasks[id].rows;return rows.every((_,i)=>answerRecord(`${id}-${i}`).status==='correct');}
function sectionComplete(i){if(i===2)return taskComplete('vocab');if(i===3)return taskComplete('choice')&&taskComplete('fill');if(i===5)return taskComplete('comprehension')&&taskComplete('truth');if(i===6)return taskComplete('present')&&taskComplete('negative')&&taskComplete('questions');if(i===7)return planPrompts.every((_,j)=>futureUsed(saved.drafts[`plan-${j}`]||'')&&(saved.drafts[`plan-${j}`]||'').trim().length>8);if(i===8)return homeworkChecks().every(c=>c.done);return true;}
function updateProgress(){saved.completed=saved.completed.filter(i=>sectionComplete(i));if([2,3,5,6,7,8].includes(current)&&sectionComplete(current)&&!saved.completed.includes(current))saved.completed.push(current);if(saved.completed.length<9)saved.finished=false;document.querySelector('#progress-count').textContent=`${saved.completed.length}/9`;document.querySelectorAll('[data-step]').forEach(b=>b.classList.toggle('complete',saved.completed.includes(Number(b.dataset.step))));}
function attemptNext(){updateProgress();if(sectionComplete(current)){if(!saved.completed.includes(current))saved.completed.push(current);}else if(current===8){document.querySelector('#homework-feedback').textContent='Заверши условия домашнего задания, чтобы закончить урок.';persist();return;}if(current<8){go(current+1);}else{if(saved.completed.length===9){saved.finished=true;render();document.querySelector('.completion')?.scrollIntoView({behavior:'smooth',block:'center'});}else{const missing=sections.map((s,i)=>({name:s[0],i})).filter(s=>!saved.completed.includes(s.i));document.querySelector('#homework-feedback').innerHTML='Домашнее задание готово. Осталось пройти: '+missing.map(s=>`<button class="text-button" data-step="${s.i}">${esc(s.name)}</button>`).join(', ')+'.';updateProgress();persist();}}}
function downloadText(type){let text='Урок 18 · Футур 1\n\n';if(type==='plan')text+=planPrompts.map((p,i)=>`${p}\n${saved.drafts[`plan-${i}`]||''}`).join('\n\n');else text+='Шта ћу радити за викенд?\n\n'+(saved.drafts.homework||'')+'\n\nБонус\n'+(saved.drafts['speech-1']||'')+'\n'+(saved.drafts['speech-2']||'');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`ty-serb-lesson18-${type}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
let strokes=[],activeStroke=null;
function paintDrawing(){const canvas=document.querySelector('#drawing');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);for(const stroke of strokes){ctx.lineWidth=stroke.width;ctx.strokeStyle=stroke.color;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();stroke.points.forEach((p,i)=>i===0?ctx.moveTo(...p):ctx.lineTo(...p));if(stroke.points.length===1){const p=stroke.points[0];ctx.lineTo(p[0]+.1,p[1]+.1);}ctx.stroke();}}
function initDrawing(){try{strokes=JSON.parse(saved.drafts.drawing||'[]');}catch{strokes=[];}const canvas=document.querySelector('#drawing');const point=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];};canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);activeStroke={width:Number(document.querySelector('#draw-width').value),color:document.querySelector('#draw-color').value,points:[point(e)]};strokes.push(activeStroke);paintDrawing();});canvas.addEventListener('pointermove',e=>{if(activeStroke){activeStroke.points.push(point(e));paintDrawing();}});const end=()=>{if(activeStroke){activeStroke=null;saved.drafts.drawing=JSON.stringify(strokes);persist();}};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);paintDrawing();}
document.addEventListener('input',e=>{const el=e.target;if(el.dataset.answer){saved.answers[el.dataset.answer]={value:el.value,status:''};const row=el.closest('.question');if(row){row.classList.remove('correct','wrong','revealed');row.querySelector('.feedback')?.remove();}persist();}if(el.dataset.draft){saved.drafts[el.dataset.draft]=el.value;persist();if(el.dataset.draft==='homework'){document.querySelector('#homework-checklist').innerHTML=renderChecklist();icons();}}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.answer){saved.answers[el.dataset.answer]={value:el.value,status:''};persist();}if(el.id==='builder-person'||el.id==='builder-verb')updateBuilder();});
function go(i){current=i;render();document.querySelector('.section-heading').scrollIntoView({behavior:'smooth',block:'start'});document.querySelector('#section-title').focus({preventScroll:true});}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.step!==undefined)go(Number(b.dataset.step));if(b.id==='previous'&&current>0)go(current-1);if(b.id==='next')attemptNext();
 if(b.dataset.frame!==undefined){frame=Number(b.dataset.frame);renderComic();}if(b.id==='comic-prev'&&frame>0){frame--;renderComic();}if(b.id==='comic-next'&&frame<7){frame++;renderComic();}if(b.id==='translation'){translated=!translated;renderComic();}
 if(b.dataset.mode){builderMode=b.dataset.mode;updateBuilder();}if(b.dataset.check)checkTask(b.dataset.check);if(b.dataset.reveal)checkTask(b.dataset.reveal,true);if(b.dataset.retry){Object.keys(saved.answers).filter(k=>k.startsWith(b.dataset.retry+'-')).forEach(k=>delete saved.answers[k]);persist();renderActivity();}
 if(b.dataset.chapter!==undefined){chapter=Number(b.dataset.chapter);renderActivity();}if(b.dataset.future){const key=b.dataset.future;saved.reading=saved.reading.includes(key)?saved.reading.filter(x=>x!==key):[...saved.reading,key];persist();renderActivity();}if(b.id==='highlight-all'){const keys=readingChapters.flatMap((c,j)=>c.join('').match(/<f>/g).map((_,i)=>`${j}-${i}`));saved.reading=saved.reading.length===keys.length?[]:keys;persist();renderActivity();}
 if(b.id==='review-plan'){const entries=planPrompts.map((_,i)=>saved.drafts[`plan-${i}`]||'');document.querySelector('#plan-feedback').textContent=entries.every(t=>futureUsed(t)&&t.trim().length>8)?'Все 6 ответов содержат форму будущего времени. Сравни смысл с вопросами.':'Ответь на все 6 вопросов и используй Футур 1 в каждом ответе.';}
 if(b.id==='review-homework'){const missing=homeworkChecks().filter(c=>!c.done);document.querySelector('#homework-feedback').textContent=missing.length?'Добавь: '+missing.map(c=>c.label).join(', ')+'.':'Все условия выполнены. Перечитай текст и проверь окончания и порядок слов.';}
 if(b.dataset.download)downloadText(b.dataset.download);if(b.id==='draw-undo'){strokes.pop();saved.drafts.drawing=JSON.stringify(strokes);paintDrawing();persist();}if(b.id==='draw-clear'){strokes=[];saved.drafts.drawing='[]';paintDrawing();persist();}if(b.id==='draw-save'){const a=document.createElement('a');a.href=document.querySelector('#drawing').toDataURL('image/png');a.download='ty-serb-lesson18-comic.png';a.click();}
});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-answer][type=text]')){e.preventDefault();checkTask(e.target.dataset.answer.replace(/-\d+$/,''));}if(e.target.matches('[role=tab]')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();chapter=(chapter+(e.key==='ArrowRight'?1:2))%3;renderActivity();document.querySelector(`#reading-tab-${chapter}`).focus();}});
if(navigator.modelContext?.registerTool){try{navigator.modelContext.registerTool({name:'get_lesson_progress',description:'Read the current section and completed sections of Ty Serb lesson 18.',inputSchema:{type:'object',properties:{}},execute:async()=>({content:[{type:'text',text:JSON.stringify({lesson:18,currentSection:current+1,completedSections:saved.completed.map(i=>i+1),sections:sections.map(s=>s[0])})}]})});navigator.modelContext.registerTool({name:'open_lesson_section',description:'Open a section of lesson 18 by its number, from 1 to 9.',inputSchema:{type:'object',properties:{section:{type:'integer',minimum:1,maximum:9}},required:['section']},execute:async({section})=>{if(!Number.isInteger(section)||section<1||section>9)throw new Error('Invalid section');go(section-1);return{content:[{type:'text',text:`Opened ${sections[section-1][0]}`}]};}});}catch{}}
saved.completed=saved.completed.filter(i=>sectionComplete(i));
render();
